backend:
  app:
    jwtSecret: backendSecretKey
    jwtExpirationMs: 3600000
    
spring:
  datasource:
    url: jdbc:postgresql://ec2-18-206-84-251.compute-1.amazonaws.com:5432/dm7qhqs06ve43?serve
    username: vhgycrutnrmkjt
    password:     b3d16ab64f6a6f3bd4c3a321d251531bac2dd40ce2b3c8cfdaa691eee1eae748
    initialization-mode: always
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
      
logging:
  level:
    com.mulyadime: DEBUG