backend:
  app:
    jwtSecret: backendSecretKey
    jwtExpirationMs: 3600000
    
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    initialization-mode: always
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
      
logging:
  level:
    com.mulyadime: DEBUG
    
server:
   port: 7932